<?xml version="1.0" encoding="utf-8"?><Database Name="SpamDB" Class="ShedulesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(localdb)\MSSQLLocalDB;Initial Catalog=SpamDB;Integrated Security=True;Pooling=False" SettingsObjectName="SpamLib.Properties.Settings" SettingsPropertyName="SpamDBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Shedules" Member="Shedule">
    <Type Name="Shedule">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Body" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>